window:
  padding:
    x: 15
    y: 15
  dynamic_padding: true
  decorations: none
  startup_mode: Fullscreen

font:
  normal:
    family: "JetBrains Mono"
    style: Regular
  bold:
    family: "JetBrains Mono"
    style: Bold
  italic:
    family: "JetBrains Mono"
    style: Italic
  bold_italic:
    family: "JetBrains Mono"
    style: Bold Italic
  size: 11.0

# Nord color scheme
colors:
  primary:
    background: "#2E3440"
    foreground: "#D8DEE9"
  normal:
    black: "#3B4252"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#88C0D0"
    white: "#E5E9F0"
  bright:
    black: "#4C566A"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#8FBCBB"
    white: "#ECEFF4"

key_bindings:
  - { key: M, mods: Shift|Alt, action: ToggleFullscreen }
